### ISSUE TITLE
Cannot find module 'parcel-bundler/src/Logger'

### ISSUE THREAD

**Issue by stuartjnelson** [lc60005457/parcel-plugin-eslint#16]
**Description**

After installing this plugin I am getting this error `Cannot find module 'parcel-bundler/src/Logger'`.

**Environment**

| Software          | Version(s) |
| ----------------- | ---------- |
| Parcel            |  1.11.0 |
| Node              | 10.14.2 |
| Yarn          | 1.12.3 |
| Operating System  | macOS 10.13.6 |
| parcel-plugin-eslint | 1.0.4 |

**Comment by mikelyncheski** [comment]
I got the same message.   A different plugin fixed the same problem using this method: 

https://github.com/shunia/parcel-plugin-json-url-loader/issues/1

**Comment by pablospaniard** [comment]
Have same issue, please update plugin ASAP. Thanks!

**Comment by tsi** [comment]
Same here

**Comment by BoltDoggy** [comment]
v1.0.6 released, that merged #15 .
