### ISSUE TITLE
eslint peer dependency version too specific

### ISSUE THREAD

**Issue by EvilHacker** [lc60005457/parcel-plugin-eslint#17]
https://github.com/BoltDoggy/parcel-plugin-eslint/blob/a8935b97b46b347bf235eda13d8bd0b54f368d0d/package.json#L27

Peer dependencies versions should be lenient and not lock you down to specific patch versions.
In this case, eslint is expected to be exactly version 5.12.x.

Depending on the `npm` command, I get a warning or error when I have any eslint version other than 5.12.1 installed.

```npm WARN parcel-plugin-eslint@1.0.6 requires a peer of eslint@~5.12.1 but none is installed. You must install peer dependencies yourself.```

```npm ERR! peer dep missing: eslint@~5.12.1, required by parcel-plugin-eslint@1.0.6```

**Comment by EvilHacker** [comment]
I submitted a pull request for this: https://github.com/EvilHacker/parcel-plugin-eslint/pull/1 .
Although, I am not entirely sure if the eslint version under  "dependencies" should be changed as well.

**Comment by BoltDoggy** [comment]
https://github.com/BoltDoggy/parcel-plugin-eslint/pull/18
v1.0.7
