### ISSUE TITLE
What does this actually do?

### ISSUE THREAD

**Issue by FalkoJoseph** [lc60005457/parcel-plugin-eslint#3]
Is it supposed to show lint errors during the build / watch process? It doesn't seem to work for me, if that's the case :)

**Comment by tkivela** [comment]
Same for me, does not currently report any errors.

**Comment by covertbert** [comment]
Same for me

**Comment by LS1231** [comment]
Same for me

**Comment by covertbert** [comment]
I check out the example too and ran it locally. It doesn't appear to do anything either!

**Comment by BoltDoggy** [comment]
1.0.3 is coming. Thanks for watch.

**Comment by tkivela** [comment]
Thanks @BoltDoggy , it works! I have a working example with Parcel, React, Eslint (with standard) here if somebody needs example: https://github.com/tkivela/parceltemplate
