### ISSUE TITLE
🚨  Cannot read property 'clear' of undefined

### ISSUE THREAD

**Issue by l-hammer** [lc60005457/parcel-plugin-eslint#7]
<!- description ->

This error occurs when eslint is saved in error, and is always present when the eslint error is resolved，how to solve? thanks~

![wechatimg81](https://user-images.githubusercontent.com/27677988/36822238-f201ed5e-1d31-11e8-83e8-9f5dee52e86d.jpeg)

<!- repo url ->

Show a repo url: https://github.com/l-hammer/YDTemplate

<!- environment ->

| Software                    | Version(s) |
| ---------------------| ---------- |
| Parcel                         | "^1.6.2"
| Vue                             | "^2.5.10"
| Node                          | "^8.8.1"
| npm/Yarn                   | "^5.6.0"
| Operating System     | "macOS High Sierra v10.13.3"

**Comment by zodiacfireworks** [comment]
Same problem here :hand:

The error I got was

```
🚨  Cannot read property 'clear' of undefined
    at Bundler.bundler.on (/path_to_my_project_folder/node_modules/parcel-plugin-eslint/index.js:22:28)
    at emitOne (events.js:116:13)
    at Bundler.emit (events.js:211:7)
    at Bundler.bundle (/path_to_my_project_folder/node_modules/parcel-bundler/src/Bundler.js:212:12)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```

Looking at the file `/path_to_my_project_folder/node_modules/parcel-plugin-eslint/index.js`, I found the following code

```
    bundler.on('bundled', () => {
        let cache;
        try {
            cache = jsonfile.readFileSync(constFile.cacheFile);
        } catch (e) {
            cache = {};
        }
        cache.log = cache.log || [];
        if (cache.log.length) {
            bundler.logger.clear(); // -->The error is fired here
        }
        cache.log.forEach(element => {
            bundler.logger.write(element);
        });

        jsonfile.writeFileSync(constFile.cacheFile, {});
    });
```

I suppose that the condition `if (cache.log.length) ...` is not sufficient to ensure the existence of `logger` in the `bundler`. Replacing such condition for something like `if (cache.log.length && bundler.logger) ...` may help.

I'm working in my first project with Parcel and Vuejs, and didn't know much about JS tooling.

Software | Version(s)
-- | --
Parcel | "^1.6.2"
Vue | "^2.5.13"
Node | "^8.9.3"
Yarn | "^1.3.2"
Operating System | "Linux Deepin 15.5"

### Update

Using `if (cache.log.length && bundler.logger) ...` raises another error in 

```
        cache.log.forEach(element => {
            bundler.logger.write(element); // -->New error is fired here
        });
```

Adding a `console.log(typeOf(bundler.logger))` shows that `bundler.logger` is never defined.

**Comment by mzabielski** [comment]
From what I investigated, in `index.js ` you should replace `bundler.logger` with `logger` and add 

`const logger = require('parcel-bundler/src/Logger');` 

to the top of file, because `Logger` instance is no longer placed as a property of `Bundler`.
